### ISSUE TITLE
JupyterWorkflow.ipynb: plt.style.use('seaborn') -> not available style in mpl 1.5.1

### ISSUE THREAD

**Issue by pamag** [jakevdp/JupyterWorkflow#7]
In jupyter notebook JupyterWorkflow.ipynb

    %matplotlib inline
    import matplotlib.pyplot as plt
    plt.style.use('seaborn')
.

    Matplotlib version = 1.5.1

The seaborn style for matplotlib is not available anymore.

    OSError: 'seaborn' not found in the style library and input is not a valid URL or path. See `style.available` for list of available styles.

Available styles:

    ['seaborn-pastel',
     'seaborn-ticks',
     'ggplot',
     'seaborn-bright',
     'seaborn-talk',
     'seaborn-notebook',
     'seaborn-deep',
     'grayscale',
     'seaborn-muted',
     'seaborn-dark-palette',
     'seaborn-colorblind',
     'bmh',
     'seaborn-poster',
     'seaborn-paper',
     'fivethirtyeight',
     'seaborn-white',
     'classic',
     'seaborn-dark',
     'seaborn-whitegrid',
     'dark_background',
     'seaborn-darkgrid']

**Comment by jakevdp** [comment]
I was using matplotib 2.0. I think if you update you will see this style available.
